### Get songs
POST http://localhost:4444/graphql
Content-Type: application/json

{
  "query": "query { songs { id title lyrics { id content } } }"
}


### Add songs
POST http://localhost:4444/graphql
Content-Type: application/json

{
  "query": "mutation { addSong(title: \"New Song\") { id title lyrics { id content } } }"
}

