### Get songs
POST http://localhost:4444/graphql
Content-Type: application/json

{
  "query": "query { songs { id title lyrics { id content } } }"
}


### Add songs
POST http://localhost:4444/graphql
Content-Type: application/json

{
  "query": "mutation { addSong(title: \"New Song\") { id title lyrics { id content } } }"
}

### Delete songs
POST http://localhost:4444/graphql
Content-Type: application/json

{
  "query": "mutation { deleteSong(id: \"695077f72b6732c0324605de\") { id title lyrics { id content } } }"
}

### Song
POST http://localhost:4444/graphql
Content-Type: application/json

{
  "query": "query { song(id: \"695073fb2b6732c0324605d5\") { id title lyrics { id content } } }"
}


### Add Lyric
POST http://localhost:4444/graphql
Content-Type: application/json

{
  "query": "mutation { addLyricToSong(content: \"New lyric\", songId: \"695073fb2b6732c0324605d5\") { id title lyrics { id content } } }"
}
