### Root query
POST http://localhost:4000/graphql
Content-Type: application/json

{
  "query": "{ posts { id text user { username avatar } } }"
}


### Mutation
POST http://localhost:4000/graphql
Content-Type: application/json

{
  "query": "mutation AddPost { addPost(post: { text: \"Hello world from GraphQL\" }) { id text user { username avatar } } }"
}